resources:
- manifests.yaml
# +kubebuilder:scaffold:webhookkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_resources.yaml
# +kubebuilder:scaffold:webhookkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_resources.yaml
# +kubebuilder:scaffold:webhookkustomizecainjectionpatch

# the following config is for teaching kustomize how to do the var substitution
vars:
# [CERTMANAGER] To enable cert-manager, uncomment all sections below with [CERTMANAGER] prefix.
#- name: CRD_CA_BUNDLE
#  objref:
#    kind: ValidatingWebhookConfiguration
#    name: validating-webhook-configuration
#    apiVersion: v1
#  path: webhooks[0].clientConfig.caBundle
#- name: CRD_CA_BUNDLE
#  objref:
#    kind: MutatingWebhookConfiguration
#    name: mutating-webhook-configuration
#    apiVersion: v1
#  path: webhooks[0].clientConfig.caBundle

