{{- if and .Values.operator.enabled .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "avapigw.webhook.serviceName" . }}
  namespace: {{ include "avapigw.namespace" . }}
  labels:
    {{- include "avapigw.operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
  selector:
    {{- include "avapigw.operator.selectorLabels" . | nindent 4 }}
{{- end }}
