apiVersion: v2
name: avapigw
description: A Helm chart for AVAPIGW - Kubernetes API Gateway Operator

type: application

version: 0.1.0

appVersion: "0.1.0"

home: https://github.com/vyrodovalexey/avapigw

sources:
  - https://github.com/vyrodovalexey/avapigw

maintainers:
  - name: Alexey Vyrodov
    email: vyrodovalexey@github.com
    url: https://github.com/vyrodovalexey

keywords:
  - api-gateway
  - kubernetes
  - operator
  - ingress
  - grpc
  - http
  - tcp
  - tls

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/prerelease: "true"

dependencies: []
