{{- if .Values.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "avapigw.operator.fullname" . }}-manager
  labels:
    {{- include "avapigw.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "avapigw.operator.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "avapigw.operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
