{{- if .Values.operator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "avapigw.operator.serviceName" . }}
  namespace: {{ include "avapigw.namespace" . }}
  labels:
    {{- include "avapigw.operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.operator.metrics.port }}
      targetPort: metrics
      protocol: TCP
    - name: health
      port: {{ .Values.operator.health.port }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "avapigw.operator.selectorLabels" . | nindent 4 }}
{{- end }}
